# Generated by Django 3.2.7 on 2021-09-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatcanido', '0003_auto_20210920_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
