# Generated by Django 3.2.7 on 2021-09-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatcanido', '0004_auto_20210923_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='effect',
        ),
        migrations.AlterField(
            model_name='data',
            name='name_slug',
            field=models.SlugField(max_length=250),
        ),
    ]
